### ISSUE TITLE
When you hit calculate without entering any numbers, it says NaN

### ISSUE THREAD

**Issue by creativitRy** [abhinavk99/439-grades#3] opened 2018-10-12 04:04 UTC
I think this is unreasonable

**Comment by abhinavk99** [comment] 2018-10-12 04:19
Yeah, I opened issue #1 since I haven't implemented any handling of bad inputs yet.

**Comment by abhinavk99** [comment] 2018-10-12 06:27
Closing as duplicate of #1

**Closed as completed by abhinavk99** 2018-10-12 06:27 UTC
Labels: duplicate
